/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.raven.main;

/**
 *
 * @author paulo
 */
public class AreaCon extends javax.swing.JFrame {

    /**
     * Creates new form AreaCon
     */
    public AreaCon() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lingTec = new javax.swing.JLabel();
        matTec = new javax.swing.JLabel();
        cieNaTec = new javax.swing.JLabel();
        ciHuTec = new javax.swing.JLabel();
        Back = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lingTec.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lingTec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lingTecMouseClicked(evt);
            }
        });
        jPanel1.add(lingTec, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 690, 70));

        matTec.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        matTec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                matTecMouseClicked(evt);
            }
        });
        jPanel1.add(matTec, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 680, 70));

        cieNaTec.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cieNaTec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cieNaTecMouseClicked(evt);
            }
        });
        jPanel1.add(cieNaTec, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, 680, 70));

        ciHuTec.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ciHuTec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ciHuTecMouseClicked(evt);
            }
        });
        jPanel1.add(ciHuTec, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 540, 680, 70));

        Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });
        jPanel1.add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 670, 150, 60));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/Telas/1.png"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1370, 770));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        dispose();
        new Home().setVisible(true);
    }//GEN-LAST:event_BackMouseClicked

    private void lingTecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lingTecMouseClicked
        dispose();
        new LingTec().setVisible(true);
    }//GEN-LAST:event_lingTecMouseClicked

    private void matTecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_matTecMouseClicked
        dispose();
        new MatTec().setVisible(true);
    }//GEN-LAST:event_matTecMouseClicked

    private void cieNaTecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cieNaTecMouseClicked
        dispose();
        new CieNaTec().setVisible(true);
    }//GEN-LAST:event_cieNaTecMouseClicked

    private void ciHuTecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ciHuTecMouseClicked
        dispose();
        new CieHuTec().setVisible(true);
    }//GEN-LAST:event_ciHuTecMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AreaCon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AreaCon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AreaCon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AreaCon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AreaCon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Back;
    private javax.swing.JLabel background;
    private javax.swing.JLabel ciHuTec;
    private javax.swing.JLabel cieNaTec;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lingTec;
    private javax.swing.JLabel matTec;
    // End of variables declaration//GEN-END:variables
}
