/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.raven.main;

import Animacion.Animacion;
import Conexao.Conexao;
import Conexao.UsuarioCRUD;
import com.raven.main.Main;
import com.raven.model.Usuario;
import java.awt.Color;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author paulo
 */
public class Home extends javax.swing.JFrame {
    /**
     * Creates new form Home
     */
    public void exportEmail(Usuario usuario) {
        label.setText(usuario.getEmail());
    }
    public Home() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        label.setVisible(false);
        LId.setVisible(false);
        PNome.setVisible(false);
        PCpf.setVisible(false);
        PForm.setVisible(false);
        PCurso.setVisible(false);
        PArea.setVisible(false);
        PEmail.setVisible(false);
        PSenha.setVisible(false);
        BtEdit.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jMenu = new javax.swing.JLabel();
        jPMenuLateral = new javax.swing.JPanel();
        PNome = new javax.swing.JLabel();
        LNome = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        PEmail = new javax.swing.JLabel();
        LEmail = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        PCpf = new javax.swing.JLabel();
        LCpf = new javax.swing.JLabel();
        PForm = new javax.swing.JLabel();
        LForm = new javax.swing.JLabel();
        PCurso = new javax.swing.JLabel();
        PArea = new javax.swing.JLabel();
        LCurAre = new javax.swing.JLabel();
        PSenha = new javax.swing.JLabel();
        LSenha = new javax.swing.JLabel();
        BtEdit = new com.raven.swing.Button();
        jSeparator7 = new javax.swing.JSeparator();
        jPHome = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jPSimul = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jPSair = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLCopy = new javax.swing.JLabel();
        jLapproved = new javax.swing.JLabel();
        LId = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbPerfil = new javax.swing.JTable();
        label = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLConte = new javax.swing.JLabel();
        jLAvali = new javax.swing.JLabel();
        jLBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/menu.png"))); // NOI18N
        jMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jMenuAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuMouseClicked(evt);
            }
        });
        jPanel2.add(jMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 50, 50));

        jPMenuLateral.setBackground(new java.awt.Color(0, 70, 81));
        jPMenuLateral.setLayout(null);

        PNome.setFont(new java.awt.Font("Fira Sans Black", 1, 12)); // NOI18N
        PNome.setForeground(new java.awt.Color(255, 255, 255));
        PNome.setText("Nome:");
        jPMenuLateral.add(PNome);
        PNome.setBounds(10, 100, 37, 16);

        LNome.setFont(new java.awt.Font("Fira Sans", 0, 12)); // NOI18N
        LNome.setForeground(new java.awt.Color(255, 255, 255));
        jPMenuLateral.add(LNome);
        LNome.setBounds(60, 98, 230, 20);
        jPMenuLateral.add(jSeparator1);
        jSeparator1.setBounds(0, 330, 290, 10);

        PEmail.setFont(new java.awt.Font("Fira Sans Black", 1, 12)); // NOI18N
        PEmail.setForeground(new java.awt.Color(255, 255, 255));
        PEmail.setText("E-mail:");
        jPMenuLateral.add(PEmail);
        PEmail.setBounds(10, 140, 50, 16);

        LEmail.setFont(new java.awt.Font("Fira Sans", 0, 12)); // NOI18N
        LEmail.setForeground(new java.awt.Color(255, 255, 255));
        jPMenuLateral.add(LEmail);
        LEmail.setBounds(60, 138, 230, 20);
        jPMenuLateral.add(jSeparator2);
        jSeparator2.setBounds(0, 120, 290, 10);

        PCpf.setFont(new java.awt.Font("Fira Sans Black", 1, 12)); // NOI18N
        PCpf.setForeground(new java.awt.Color(255, 255, 255));
        PCpf.setText("CPF:");
        jPMenuLateral.add(PCpf);
        PCpf.setBounds(10, 180, 30, 16);

        LCpf.setFont(new java.awt.Font("Fira Sans", 0, 12)); // NOI18N
        LCpf.setForeground(new java.awt.Color(255, 255, 255));
        jPMenuLateral.add(LCpf);
        LCpf.setBounds(40, 180, 200, 20);

        PForm.setFont(new java.awt.Font("Fira Sans Black", 1, 12)); // NOI18N
        PForm.setForeground(new java.awt.Color(255, 255, 255));
        PForm.setText("Formacao:");
        jPMenuLateral.add(PForm);
        PForm.setBounds(10, 220, 61, 16);

        LForm.setFont(new java.awt.Font("Fira Sans", 0, 12)); // NOI18N
        LForm.setForeground(new java.awt.Color(255, 255, 255));
        jPMenuLateral.add(LForm);
        LForm.setBounds(80, 218, 210, 20);

        PCurso.setFont(new java.awt.Font("Fira Sans Black", 1, 12)); // NOI18N
        PCurso.setForeground(new java.awt.Color(255, 255, 255));
        PCurso.setText("Curso:");
        jPMenuLateral.add(PCurso);
        PCurso.setBounds(10, 260, 40, 16);

        PArea.setFont(new java.awt.Font("Fira Sans Black", 1, 12)); // NOI18N
        PArea.setForeground(new java.awt.Color(255, 255, 255));
        PArea.setText("Área:");
        jPMenuLateral.add(PArea);
        PArea.setBounds(10, 260, 31, 16);

        LCurAre.setFont(new java.awt.Font("Fira Sans", 0, 12)); // NOI18N
        LCurAre.setForeground(new java.awt.Color(255, 255, 255));
        jPMenuLateral.add(LCurAre);
        LCurAre.setBounds(60, 260, 237, 20);

        PSenha.setFont(new java.awt.Font("Fira Sans Black", 1, 12)); // NOI18N
        PSenha.setForeground(new java.awt.Color(255, 255, 255));
        PSenha.setText("Senha:");
        jPMenuLateral.add(PSenha);
        PSenha.setBounds(10, 300, 40, 16);

        LSenha.setFont(new java.awt.Font("Fira Sans", 0, 12)); // NOI18N
        LSenha.setForeground(new java.awt.Color(255, 255, 255));
        jPMenuLateral.add(LSenha);
        LSenha.setBounds(60, 300, 90, 16);

        BtEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/editarB.png"))); // NOI18N
        BtEdit.setText("Editar Perfil");
        BtEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtEditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtEditMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BtEditMouseReleased(evt);
            }
        });
        BtEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtEditActionPerformed(evt);
            }
        });
        jPMenuLateral.add(BtEdit);
        BtEdit.setBounds(80, 360, 110, 26);
        jPMenuLateral.add(jSeparator7);
        jSeparator7.setBounds(0, 420, 290, 10);

        jPHome.setBackground(new java.awt.Color(0, 70, 81));
        jPHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPHome.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPHomeMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPHomeMouseMoved(evt);
            }
        });
        jPHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPHomeMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPHomeMouseReleased(evt);
            }
        });
        jPHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/Ícone-Casa-PNG (2).png"))); // NOI18N
        jPHome.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 28));

        jLabel4.setFont(new java.awt.Font("Fira Sans", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Home");
        jPHome.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jPMenuLateral.add(jPHome);
        jPHome.setBounds(0, 440, 290, 50);
        jPMenuLateral.add(jSeparator8);
        jSeparator8.setBounds(0, 500, 290, 10);

        jPSimul.setBackground(new java.awt.Color(0, 70, 81));
        jPSimul.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPSimul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPSimulMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPSimulMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPSimulMouseExited(evt);
            }
        });
        jPSimul.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/Novo Projeto.png"))); // NOI18N
        jPSimul.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 40));

        jLabel6.setFont(new java.awt.Font("Fira Sans", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Prova / Simulado");
        jPSimul.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, 30));

        jPMenuLateral.add(jPSimul);
        jPSimul.setBounds(0, 520, 290, 60);
        jPMenuLateral.add(jSeparator9);
        jSeparator9.setBounds(0, 590, 290, 20);

        jPSair.setBackground(new java.awt.Color(0, 70, 81));
        jPSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPSairMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPSairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPSairMouseExited(evt);
            }
        });
        jPSair.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/back.png"))); // NOI18N
        jPSair.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 40));

        jLabel1.setFont(new java.awt.Font("Fira Sans", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Exit");
        jPSair.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, 30));

        jPMenuLateral.add(jPSair);
        jPSair.setBounds(0, 610, 290, 60);

        jLCopy.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLCopy.setForeground(new java.awt.Color(255, 255, 255));
        jLCopy.setText("Copyright © Higher Devellop");
        jPMenuLateral.add(jLCopy);
        jLCopy.setBounds(70, 680, 170, 40);

        jLapproved.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLapproved.setForeground(new java.awt.Color(255, 255, 255));
        jLapproved.setText("Approved Software");
        jPMenuLateral.add(jLapproved);
        jLapproved.setBounds(100, 700, 100, 30);
        jPMenuLateral.add(LId);
        LId.setBounds(50, 100, 0, 0);

        TbPerfil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "null", "null", "null", "null", "null", "null", "null"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TbPerfil);
        if (TbPerfil.getColumnModel().getColumnCount() > 0) {
            TbPerfil.getColumnModel().getColumn(0).setResizable(false);
            TbPerfil.getColumnModel().getColumn(1).setResizable(false);
            TbPerfil.getColumnModel().getColumn(2).setResizable(false);
            TbPerfil.getColumnModel().getColumn(3).setResizable(false);
            TbPerfil.getColumnModel().getColumn(4).setResizable(false);
            TbPerfil.getColumnModel().getColumn(5).setResizable(false);
            TbPerfil.getColumnModel().getColumn(6).setResizable(false);
        }

        jPMenuLateral.add(jScrollPane1);
        jScrollPane1.setBounds(150, 320, 0, 0);
        jPMenuLateral.add(label);
        label.setBounds(290, 180, 0, 0);
        jPMenuLateral.add(jSeparator3);
        jSeparator3.setBounds(0, 170, 290, 10);
        jPMenuLateral.add(jSeparator4);
        jSeparator4.setBounds(0, 210, 290, 10);
        jPMenuLateral.add(jSeparator5);
        jSeparator5.setBounds(0, 250, 290, 10);
        jPMenuLateral.add(jSeparator6);
        jSeparator6.setBounds(0, 290, 290, 10);

        jPanel2.add(jPMenuLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(-300, 0, 290, 770));

        jLConte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLConte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLConteMouseClicked(evt);
            }
        });
        jPanel2.add(jLConte, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 530, 440, 80));

        jLAvali.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLAvali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLAvaliMouseClicked(evt);
            }
        });
        jPanel2.add(jLAvali, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 340, 440, 90));

        jLBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/Bem vindo.png"))); // NOI18N
        jPanel2.add(jLBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPSairMouseClicked
        dispose();
    }//GEN-LAST:event_jPSairMouseClicked

    private void jPSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPSairMouseEntered
        jPSair.setBackground(Color.red);
    }//GEN-LAST:event_jPSairMouseEntered

    private void jPSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPSairMouseExited
        jPSair.setBackground(UIManager.getColor("[54,70,78]"));
    }//GEN-LAST:event_jPSairMouseExited

    private void jPHomeMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPHomeMouseDragged

    }//GEN-LAST:event_jPHomeMouseDragged

    private void jPHomeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPHomeMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jPHomeMouseMoved

    private void jPHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPHomeMouseClicked

    }//GEN-LAST:event_jPHomeMouseClicked

    private void jPHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPHomeMouseEntered
        jPHome.setBackground(Color.black);
    }//GEN-LAST:event_jPHomeMouseEntered

    private void jPHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPHomeMouseExited
        jPHome.setBackground(UIManager.getColor("[54,70,78]"));
    }//GEN-LAST:event_jPHomeMouseExited

    private void jPHomeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPHomeMouseReleased

    }//GEN-LAST:event_jPHomeMouseReleased

    private void jPSimulMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPSimulMouseClicked


    }//GEN-LAST:event_jPSimulMouseClicked

    private void jPSimulMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPSimulMouseEntered
        jPSimul.setBackground(Color.black);
    }//GEN-LAST:event_jPSimulMouseEntered

    private void jPSimulMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPSimulMouseExited
        jPSimul.setBackground(UIManager.getColor("[54,70,78]"));
    }//GEN-LAST:event_jPSimulMouseExited

    private void jMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuMouseClicked
        int  x = jPMenuLateral.getX();
        if (x <= -210) {
            Animacion.mover_derecha(10, 220, 15, 8, jMenu);
            Animacion.mover_derecha(-300, 0, 8, 8, jPMenuLateral);
       }else{
            Animacion.mover_izquierda(220, 10, 4, 2, jMenu);
            Animacion.mover_izquierda(0, -300, 2, 2, jPMenuLateral);
        }
        
        showPerfil();
        PNome.setVisible(true);
        PCpf.setVisible(true);
        PForm.setVisible(true);
        if("Aluno".equals((TbPerfil.getModel().getValueAt(0, 3).toString()))){
            PCurso.setVisible(true);
        } else {
            PArea.setVisible(true);
        }        
        PEmail.setVisible(true);
        PSenha.setVisible(true);
        BtEdit.setVisible(true);
        LoadPerfil();
    }//GEN-LAST:event_jMenuMouseClicked

    private void jMenuAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jMenuAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuAncestorAdded

    private void BtEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtEditActionPerformed
        dispose();
        Usuario usuario = new Usuario();
        usuario.setNome(LNome.getText());
        usuario.setId(Integer.parseInt(LId.getText()));
        usuario.setEmail(LEmail.getText());
        usuario.setCpf(LCpf.getText());
        usuario.setFormacao(LForm.getText());
        usuario.setCursarea(LCurAre.getText());
        usuario.setSenha(LSenha.getText());
        UpdatePerfil home = new UpdatePerfil();
        home.exportInfo(usuario);
        home.setVisible(true);
    }//GEN-LAST:event_BtEditActionPerformed

    private void jLConteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLConteMouseClicked
        dispose();
        new AreaCon().setVisible(true);
    }//GEN-LAST:event_jLConteMouseClicked

    private void jLAvaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLAvaliMouseClicked
        dispose();
        new AreaAval().setVisible(true);
    }//GEN-LAST:event_jLAvaliMouseClicked

    private void BtEditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtEditMouseEntered
    BtEdit.setBackground(Color.black);
    BtEdit.setForeground(Color.white);
    BtEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/editarW.png")));
    }//GEN-LAST:event_BtEditMouseEntered

    private void BtEditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtEditMouseExited
        BtEdit.setBackground(Color.white);
        BtEdit.setForeground(Color.black);
        BtEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/editarB.png")));
    }//GEN-LAST:event_BtEditMouseExited

    private void BtEditMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtEditMouseReleased
        
    }//GEN-LAST:event_BtEditMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.swing.Button BtEdit;
    private javax.swing.JLabel LCpf;
    private javax.swing.JLabel LCurAre;
    private javax.swing.JLabel LEmail;
    private javax.swing.JLabel LForm;
    private javax.swing.JLabel LId;
    private javax.swing.JLabel LNome;
    private javax.swing.JLabel LSenha;
    private javax.swing.JLabel PArea;
    private javax.swing.JLabel PCpf;
    private javax.swing.JLabel PCurso;
    private javax.swing.JLabel PEmail;
    private javax.swing.JLabel PForm;
    private javax.swing.JLabel PNome;
    private javax.swing.JLabel PSenha;
    public javax.swing.JTable TbPerfil;
    private javax.swing.JLabel jLAvali;
    private javax.swing.JLabel jLBackground;
    private javax.swing.JLabel jLConte;
    private javax.swing.JLabel jLCopy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLapproved;
    private javax.swing.JLabel jMenu;
    private javax.swing.JPanel jPHome;
    private javax.swing.JPanel jPMenuLateral;
    private javax.swing.JPanel jPSair;
    private javax.swing.JPanel jPSimul;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel label;
    // End of variables declaration//GEN-END:variables

    private void LoadPerfil(){
        int set = 0;
        LId.setText(TbPerfil.getModel().getValueAt(set, 0).toString());
        LNome.setText(TbPerfil.getModel().getValueAt(set, 1).toString());
        LCpf.setText(TbPerfil.getModel().getValueAt(set, 2).toString());
        LForm.setText(TbPerfil.getModel().getValueAt(set, 3).toString());
        LCurAre.setText(TbPerfil.getModel().getValueAt(set, 4).toString());
        LEmail.setText(TbPerfil.getModel().getValueAt(set, 5).toString());
        LSenha.setText(TbPerfil.getModel().getValueAt(set, 6).toString());        
    }
    
    private void showPerfil(){
        try {
            Usuario usuario = new Usuario();
            Connection connection = new Conexao().getConnection();
            UsuarioCRUD usuariocrud = new UsuarioCRUD(connection);

            DefaultTableModel model = (DefaultTableModel) TbPerfil.getModel();
            model.setNumRows(0);

            String email = label.getText();
            usuario.setEmail(email);
            
            ArrayList<Usuario> lista = usuariocrud.showUser(usuario);
            for (int num = 0; num < lista.size(); num++) {
            model.addRow(new Object[]{
                lista.get(num).getId(),
                lista.get(num).getNome(),
                lista.get(num).getCpf(),
                lista.get(num).getFormacao(),
                lista.get(num).getCursarea(),
                lista.get(num).getEmail(),
                lista.get(num).getSenha(),
            });
            }   
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    
}
