/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.raven.main;

import Conexao.Conexao;
import Conexao.UsuarioCRUD;
import com.raven.model.Usuario;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JComboBox;

/**
 *
 * @author paulo
 */
public class UpdatePerfil extends javax.swing.JFrame {
        
    /**
     * Creates new form UpdatePerfil
     */
    public UpdatePerfil() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        txtId.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNome = new javax.swing.JTextField();
        txtCpf = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtSenha = new javax.swing.JTextField();
        combobox1 = new javax.swing.JComboBox<>();
        combobox2 = new javax.swing.JComboBox<>();
        back = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        txtId = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNome.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel1.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 104, 654, 53));

        txtCpf.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtCpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCpfKeyTyped(evt);
            }
        });
        jPanel1.add(txtCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 374, 654, 53));

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 197, 654, 53));

        txtSenha.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel1.add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 285, 654, 53));

        combobox1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        combobox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aluno", "Professor" }));
        combobox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combobox1ItemStateChanged(evt);
            }
        });
        combobox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                combobox1MouseClicked(evt);
            }
        });
        combobox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobox1ActionPerformed(evt);
            }
        });
        jPanel1.add(combobox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 465, 654, 53));

        combobox2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel1.add(combobox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 560, 654, 53));

        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 670, 150, 60));

        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 645, 260, 90));

        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 645, 260, 90));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/Telas/Edit.png"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(txtId)
                .addContainerGap(1327, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtId)
                .addContainerGap(748, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCpfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCpfKeyTyped
        StringBuilder cpf = new StringBuilder(txtCpf.getText());
        if ((cpf).length() > 2 && (cpf).length() < 4) {
            txtCpf.setText(cpf+".");
        }else if((cpf).length() > 6 && (cpf).length() < 8){
            txtCpf.setText(cpf+".");
        }else if((cpf).length() > 10 && (cpf).length() < 12){
            txtCpf.setText(cpf+"-");
        }else if((cpf).length() == 14){
            cpf.deleteCharAt(13);
            txtCpf.setText(cpf+"");
        }else if((cpf).length() == 12){
            cpf.deleteCharAt(11);
            txtCpf.setText(cpf+"");
        }else if((cpf).length() == 8){
            cpf.deleteCharAt(7);
            txtCpf.setText(cpf+"");
        }else if((cpf).length() == 4){
            cpf.deleteCharAt(3);
            txtCpf.setText(cpf+"");
        }
    }//GEN-LAST:event_txtCpfKeyTyped
    public void exportInfo(Usuario usuario) {
        txtEmail.setText(usuario.getEmail());
        txtNome.setText(usuario.getNome());
        txtId.setText(Integer.toString(usuario.getId()));
        txtCpf.setText(usuario.getCpf());
        txtSenha.setText(usuario.getSenha());
        combobox1.setSelectedItem(usuario.getFormacao());
        combobox2.setSelectedItem(usuario.getCursarea());
    }
    private void combobox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox1ActionPerformed
        String display = combobox1.getSelectedItem().toString();
        switch (display) {
            case "Aluno":
                Vestibulando();
                break;
            case "Professor":
                Professor();
                break;
        }
    }//GEN-LAST:event_combobox1ActionPerformed

    private void combobox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combobox1MouseClicked
        
    }//GEN-LAST:event_combobox1MouseClicked

    private void combobox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combobox1ItemStateChanged
        
    }//GEN-LAST:event_combobox1ItemStateChanged

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        try {
            Update();
        } catch (SQLException ex) {
            Logger.getLogger(UpdatePerfil.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
        new Home().setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        dispose();
        new Home().setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdatePerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdatePerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdatePerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdatePerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdatePerfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel background;
    private javax.swing.JComboBox<String> combobox1;
    private javax.swing.JComboBox<String> combobox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JLabel txtId;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSenha;
    // End of variables declaration//GEN-END:variables
    private void Update() throws SQLException{
        String nome, cpf, formacao, cursarea, email, senha;
        int id;
        
        if("".equals(txtId.getText())){
            JOptionPane.showMessageDialog(null, "Selecione um Usuário.");
        }
        id = Integer.parseInt(txtId.getText());
        nome = txtNome.getText();
        cpf = txtCpf.getText();
        formacao = combobox1.getSelectedItem().toString();
        cursarea = combobox2.getSelectedItem().toString();
        email = txtEmail.getText();
        senha = txtSenha.getText();
        
        Usuario usuario = new Usuario();
        
        usuario.setId(id);
        usuario.setNome(nome);
        usuario.setEmail(email);
        usuario.setCpf(cpf);
        usuario.setFormacao(formacao);
        usuario.setCursarea(cursarea);
        usuario.setSenha(senha);
        
        if("".equals(email) || "".equals(senha) || "".equals(nome) || "".equals(cpf)){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos.");
        }else if(!isValidEmailAddressRegex(email)){
            JOptionPane.showMessageDialog(null, "Você não digitou um tipo email.");
        }else if(!isValidCPFRegex(cpf)){
            JOptionPane.showMessageDialog(null, "Você não digitou um tipo CPF.");
        }else if((senha).length() < 8){
            JOptionPane.showMessageDialog(null, "Sua senha deve conter no mínimo 8 caracteres.");
        }else {
            dispose();
            usuario.setEmail(txtEmail.getText());
            Home home = new Home();
            home.exportEmail(usuario);
            home.setVisible(true);
            Connection connection = new Conexao().getConnection();
            UsuarioCRUD usuariocrud = new UsuarioCRUD(connection);
            usuariocrud.update(usuario);
        }
    }
    public static boolean isValidEmailAddressRegex(String email) {
    boolean isEmailIdValid = false;
    if (email != null && email.length() > 0) {
        String expression = "^[\\w\\.-]+@([\\w\\-]+\\.)+[A-Z]{2,4}$";
        Pattern pattern = Pattern.compile(expression, Pattern.CASE_INSENSITIVE);
        Matcher matcher = pattern.matcher(email);
        if (matcher.matches()) {
            isEmailIdValid = true;
        }
    }
    return isEmailIdValid;
    }
    public static boolean isValidCPFRegex(String email) {
    boolean isCPFIdValid = false;
    if (email != null && email.length() > 0) {
        String expression = "^([0-9]{3}+\\.)?([0-9]{3}+\\.)?([0-9]{3}+-)?([0-9]{2})$";
        Pattern pattern = Pattern.compile(expression, Pattern.CASE_INSENSITIVE);
        Matcher matcher = pattern.matcher(email);
        if (matcher.matches()) {
            isCPFIdValid = true;
        }
    }
    return isCPFIdValid;
    }
    private void Vestibulando(){
        combobox2.removeAllItems();
        combobox2.addItem("Agropecuária");
combobox2.addItem("Alimentos");
combobox2.addItem("Análise de Dados");
combobox2.addItem("Análise e Desenvolvimento de Sistemas");
combobox2.addItem("Apicultura e Meliponicultura");
combobox2.addItem("Aquicultura");
combobox2.addItem("Arqueologia");
combobox2.addItem("Arquitetura de Dados");
combobox2.addItem("Artes do Espetáculo");
combobox2.addItem("Artes e Mídias Digitais");
combobox2.addItem("Assessoria Executiva Digital");
combobox2.addItem("Atividades de Inteligência e Gestão de Sigilos");
combobox2.addItem("Auditoria em Saúde");
combobox2.addItem("Automação de Escritórios e Secretariado");
combobox2.addItem("Automação e Manufatura Digital");
combobox2.addItem("Automação Industrial");
combobox2.addItem("Banco de Dados");
combobox2.addItem("Big Data e Inteligência Analítica");
combobox2.addItem("Big Data no Agronegócio");
combobox2.addItem("Biocombustíveis");
combobox2.addItem("Bioenergia");
combobox2.addItem("Bioinformática");
combobox2.addItem("Biotecnologia");
combobox2.addItem("Blockchain e Criptografia Digital");
combobox2.addItem("Cafeicultura");
combobox2.addItem("Cibersegurança");
combobox2.addItem("Ciência de Dados");
combobox2.addItem("Cinema e Audiovisual");
combobox2.addItem("Coach Digital");
combobox2.addItem("Coaching e Mentoring");
combobox2.addItem("Coding");
combobox2.addItem("Comércio Exterior");
combobox2.addItem("Computação em Nuvem");
combobox2.addItem("Comunicação Assistiva");
combobox2.addItem("Comunicação Digital");
combobox2.addItem("Comunicação em Computação Gráfica");
combobox2.addItem("Comunicação em Mídias Digitais");
combobox2.addItem("Comunicação Institucional");
combobox2.addItem("Conservação e Restauro");
combobox2.addItem("Construção Civil");
combobox2.addItem("Construção de Edifícios");
combobox2.addItem("Construção Naval");
combobox2.addItem("Controle Ambiental ");
combobox2.addItem("Controle de Obras");
combobox2.addItem("Cosmetologia e Estética");
combobox2.addItem("Cozinha Contemporânea");
combobox2.addItem("Data Science");
combobox2.addItem("Defesa Cibernética");
combobox2.addItem("Defesa Médica Hospitalar");
combobox2.addItem("Desenho de Animação");
combobox2.addItem("Desenvolvimento Back-End");
combobox2.addItem("Desenvolvimento de Aplicativos para Dispositivos Móveis");
combobox2.addItem("Desenvolvimento de Produtos Plásticos");
combobox2.addItem("Desenvolvimento de Sistemas");
combobox2.addItem("Desenvolvimento e Gestão de Startups");
combobox2.addItem("Desenvolvimento Mobile");
combobox2.addItem("Desenvolvimento para Internet");
combobox2.addItem("Desenvolvimento para Web");
combobox2.addItem("Design");
combobox2.addItem("Design Comercial");
combobox2.addItem("Design de Animação");
combobox2.addItem("Design de Aplicações e Interfaces Digitais");
combobox2.addItem("Design de Experiência e de Serviços");
combobox2.addItem("Design de Games");
combobox2.addItem("Design de Interiores");
combobox2.addItem("Design de Moda");
combobox2.addItem("Design de Produto");
combobox2.addItem("Design Editorial");
combobox2.addItem("Design Educacional");
combobox2.addItem("Design Gráfico");
combobox2.addItem("Devops");
combobox2.addItem("Digital Influencer");
combobox2.addItem("Digital Security");
combobox2.addItem("E-Commerce");
combobox2.addItem("Educação e Processos de Trabalho: Alimentação Escolar");
combobox2.addItem("Educador Social");
combobox2.addItem("Eletrônica Automotiva");
combobox2.addItem("Eletrônica Industrial");
combobox2.addItem("Eletrotécnica Industrial");
combobox2.addItem("Embelezamento e Imagem Pessoal");
combobox2.addItem("Empreendedorismo");
combobox2.addItem("Energias Renováveis");
combobox2.addItem("Escrita Criativa");
combobox2.addItem("Estética e Cosmética");
combobox2.addItem("Estilismo");
combobox2.addItem("Estradas");
combobox2.addItem("Eventos");
combobox2.addItem("Fabricação Mecânica");
combobox2.addItem("Filmmaker");
combobox2.addItem("Finanças, Blockchain e Criptomoedas");
combobox2.addItem("Fitoterapia");
combobox2.addItem("Fotografia");
combobox2.addItem("Fruticultura");
combobox2.addItem("Futebol");
combobox2.addItem("Game Design");
combobox2.addItem("Gastronomia");
combobox2.addItem("Geoprocessamento");
combobox2.addItem("Gerenciamento de Redes de Computadores");
combobox2.addItem("Gerontologia");
combobox2.addItem("Gestão Ambiental");
combobox2.addItem("Gestão Comercial");
combobox2.addItem("Gestão Cultural");
combobox2.addItem("Gestão da Avaliação");
combobox2.addItem("Gestão da Inovação e Empreendedorismo Digital");
combobox2.addItem("Gestão da Produção Industrial");
combobox2.addItem("Gestão da Qualidade");
combobox2.addItem("Gestão da Segurança Pública e Patrimonial");
combobox2.addItem("Gestão das Organizações do Terceiro Setor");
combobox2.addItem("Gestão das Relações Eletrônicas");
combobox2.addItem("Gestão da Tecnologia da Informação");
combobox2.addItem("Gestão de Agronegócios");
combobox2.addItem("Gestão de Cidades Inteligentes");
combobox2.addItem("Gestão de Cloud Computing");
combobox2.addItem("Gestão de Cooperativas");
combobox2.addItem("Gestão de Energia e Eficiência Energética");
combobox2.addItem("Gestão de Equinocultura");
combobox2.addItem("Gestão de Inventário Extrajudicial");
combobox2.addItem("Gestão de Investimentos");
combobox2.addItem("Gestão de Lojas e Pontos de Vendas");
combobox2.addItem("Gestão de Mercado de Capitais");
combobox2.addItem("Gestão de Micro e Pequenas Empresas");
combobox2.addItem("Gestão de Negócios");
combobox2.addItem("Gestão de Pessoas");
combobox2.addItem("Gestão de Produção Industrial");
combobox2.addItem("Gestão de Qualidade na Saúde");
combobox2.addItem("Gestão de Recursos Hídricos");
combobox2.addItem("Gestão de Recursos Humanos");
combobox2.addItem("Gestão de Representação Comercial");
combobox2.addItem("Gestão de Resíduos de Serviços de Saúde");
combobox2.addItem("Gestão de Saúde Pública");
combobox2.addItem("Gestão de Segurança Privada");
combobox2.addItem("Gestão de Seguros");
combobox2.addItem("Gestão de Serviços Judiciários e Notariais");
combobox2.addItem("Gestão Desportiva e de Lazer");
combobox2.addItem("Gestão de Telecomunicações");
combobox2.addItem("Gestão de Trânsito");
combobox2.addItem("Gestão de Turismo");
combobox2.addItem("Gestão Empresarial");
combobox2.addItem("Gestão em Serviços");
combobox2.addItem("Gestão Financeira");
combobox2.addItem("Gestão Hospitalar");
combobox2.addItem("Gestão Portuária");
combobox2.addItem("Gestão Pública");
combobox2.addItem("Gestão Tributária");
combobox2.addItem("Horticultura");
combobox2.addItem("Hotelaria");
combobox2.addItem("Informática");
combobox2.addItem("Informática para Negócios");
combobox2.addItem("Instalações Elétricas");
combobox2.addItem("Instrumentação Cirúrgica");
combobox2.addItem("Inteligência Artificial");
combobox2.addItem("Interiores e Decorações");
combobox2.addItem("Internet das Coisas");
combobox2.addItem("Investigação e Perícia Criminal");
combobox2.addItem("Irrigação e Drenagem");
combobox2.addItem("Jogos Digitais");
combobox2.addItem("Laticínios");
combobox2.addItem("Logística");
combobox2.addItem("Luteria");
combobox2.addItem("Manufatura Avançada");
combobox2.addItem("Manutenção de Aeronaves");
combobox2.addItem("Manutenção Industrial");
combobox2.addItem("Marketing");
combobox2.addItem("Massoterapia");
combobox2.addItem("Mecânica Automobilística");
combobox2.addItem("Mecânica de Precisão");
combobox2.addItem("Mecânica");
combobox2.addItem("Mecatrônica Automotiva");
combobox2.addItem("Mecatrônica Industrial");
combobox2.addItem("Mediação");
combobox2.addItem("Microeletrônica");
combobox2.addItem("Mídias Sociais");
combobox2.addItem("Mineração");
combobox2.addItem("Ministério Pastoral");
combobox2.addItem("Moda");
combobox2.addItem("Multidisciplinar em Dependência Química");
combobox2.addItem("Negócios Digitais");
combobox2.addItem("Negócios Imobiliários");
combobox2.addItem("Oftálmica");
combobox2.addItem("Óptica e Optometria");
combobox2.addItem("Paisagismo");
combobox2.addItem("Papel e Celulose");
combobox2.addItem("Paramedicina");
combobox2.addItem("Petróleo e Gás");
combobox2.addItem("Pilotagem Profissional de Aeronaves");
combobox2.addItem("Planejamento Logístico de Cargas");
combobox2.addItem("Podologia");
combobox2.addItem("Polímeros");
combobox2.addItem("Política e Gestão Cultural");
combobox2.addItem("Políticas e Estratégicas Públicas");
combobox2.addItem("Práticas Integrativas e Complementares");
combobox2.addItem("Processamento de Dados");
combobox2.addItem("Processos Ambientais");
combobox2.addItem("Processos Escolares");
combobox2.addItem("Processos Gerenciais");
combobox2.addItem("Processos Metalúrgicos");
combobox2.addItem("Processos Químicos");
combobox2.addItem("Produção Agrícola");
combobox2.addItem("Produção Agropecuária");
combobox2.addItem("Produção Audiovisual");
combobox2.addItem("Produção Cervejeira");
combobox2.addItem("Produção Cultural");
combobox2.addItem("Produção de Cacau e Chocolate");
combobox2.addItem("Produção de Cachaça");
combobox2.addItem("Produção de Fármacos");
combobox2.addItem("Produção de Grãos");
combobox2.addItem("Produção de Plástico");
combobox2.addItem("Produção Fonográfica");
combobox2.addItem("Produção Gráfica");
combobox2.addItem("Produção Industrial");
combobox2.addItem("Produção Leiteira");
combobox2.addItem("Produção Multimídia");
combobox2.addItem("Produção Musical");
combobox2.addItem("Produção Pesqueira");
combobox2.addItem("Produção Publicitária");
combobox2.addItem("Produção Sucroalcooleira");
combobox2.addItem("Produção Têxtil");
combobox2.addItem("Projeto de Estruturas Aeronáuticas");
combobox2.addItem("Projetos Mecânicos");
combobox2.addItem("Qualidade de Vida na Contemporaneidade");
combobox2.addItem("Quiropraxia");
combobox2.addItem("Radiologia");
combobox2.addItem("Redes de Computadores");
combobox2.addItem("Refrigeração e Climatização");
combobox2.addItem("Rochas Ornamentais");
combobox2.addItem("Saneamento Ambiental");
combobox2.addItem("Saúde Coletiva");
combobox2.addItem("Secretariado");
combobox2.addItem("Segurança Alimentar");
combobox2.addItem("Segurança no Trabalho");
combobox2.addItem("Service Design");
combobox2.addItem("Silvicultura");
combobox2.addItem("Sistema de Informação");
combobox2.addItem("Sistemas Automotivos");
combobox2.addItem("Sistemas Biomédicos");
combobox2.addItem("Sistemas para Internet");
combobox2.addItem("Soldagem");
combobox2.addItem("Streaming Profissional");
combobox2.addItem("Tecnologia da Informação");
combobox2.addItem("Tecnologia Eletrônica");
combobox2.addItem("Tecnologia em Controle Ambiental");
combobox2.addItem("Tecnologia Mecânica");
combobox2.addItem("Tecnologias Educacionais");
combobox2.addItem("Telemática");
combobox2.addItem("Terapias Integrativas e Complementares");
combobox2.addItem("Toxicologia Ambiental");
combobox2.addItem("Trânsito");
combobox2.addItem("Transporte Terrestre");
combobox2.addItem("Turismo");
combobox2.addItem("Tutoria de Educação a Distância");
combobox2.addItem("Varejo Digital");
combobox2.addItem("Visagismo e Terapias Capilares");
combobox2.addItem("Viticultura e Enologia");
    }
    private void Professor(){
        combobox2.removeAllItems();
combobox2.addItem("Artes");
combobox2.addItem("Educação Física");
combobox2.addItem("Filosofia");
combobox2.addItem("Sociologia");
combobox2.addItem("Inglês");
combobox2.addItem("Física");
combobox2.addItem("Química");
combobox2.addItem("Biologia");
combobox2.addItem("Geografia");
combobox2.addItem("História");
combobox2.addItem("Matemática");
combobox2.addItem("Língua Portuguesa");
    }
}
